
workflows:
  android-release:
    name: Build Android APK
    max_build_duration: 30
    environment:
      android:
        gradle: 7.5
      java: 11
    scripts:
      - ./gradlew clean
      - ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
